### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by dzarlax** [fabtesta/synology-surveillance-api-motion-telegram-gifs#2]
Hi!
I'm trying to run this code, but constantly gets an error.

```
Traceback (most recent call last):
  File "/Users/dzarlax/PycharmProjects/notifier/syno_telegram_gifs.py", line 308, in <module>
    main()
  File "/Users/dzarlax/PycharmProjects/notifier/syno_telegram_gifs.py", line 299, in main
    camera_handler.poll_event()
  File "/Users/dzarlax/PycharmProjects/notifier/syno_telegram_gifs.py", line 229, in poll_event
    event_id = event_data['event_id']
TypeError: 'int' object is not subscriptable
```
Here is my config file.
```
{
  "data_folder": "data",
  "synology_base_api_url": "XXX",
  "synology_user": "XXX",
  "synology_password": "XXX",
  "synology_cameras": [{
    "id": 2,
    "name": "XXX"
  }],
  "telegram_bot_token": "XXX",
  "chat_id": "XXX"
}
```

**Comment by fabtesta** [comment]
Hi,
seems some python version problem. Check if you are using Python 3.7.

**Comment by dzarlax** [comment]
I already rewrite everything on the base or your MQTT service =) 
In test now!
